security:
    encoders:
        Yomaah\connexionBundle\Entity\User : sha256

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        administrateur : ROLE_ADMIN
        visiteur : ROLE_USER
        super_admin : ROLE_SUPER_ADMIN

    providers:
        main:
            entity: { class : Yomaah\connexionBundle\Entity\User, property : login }
    # in_memory:
    #        memory:
    #            users:
    #                user:  { password: userpass, roles: [ 'ROLE_USER' ] }
    #                admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
      # dev:
      #      pattern:  ^/(_(profiler|wdt)|css|images|js)/
      #      security: false

      #  login:
      #      pattern:  ^/demo/secured/login$
      #      security: false

        secured_area:
            pattern:    ^/
            form_login:
                check_path: /login_check
                login_path: /login
            logout:
                path:   /logout
                target: /
            anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin*, roles: ROLE_ADMIN }
