<?php

namespace Yomaah\connexionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepo extends EntityRepository
{
    public function findByGroup($param)
    {
        $sql = 'select U,g from YomaahconnexionBundle:User U join U.group g where g.idGroup=:idGroup';
        return $this->getEntityManager()->createQuery($sql)->setParameter('idGroup', $param['idGroup'])->getResult();
    }
}
