<?php

namespace Proxies\__CG__\EuroLiterie\structureBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Marque extends \EuroLiterie\structureBundle\Entity\Marque implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setIdMarque($idMarque)
    {
        $this->__load();
        return parent::setIdMarque($idMarque);
    }

    public function getIdMarque()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idMarque"];
        }
        $this->__load();
        return parent::getIdMarque();
    }

    public function setNomMarque($nomMarque)
    {
        $this->__load();
        return parent::setNomMarque($nomMarque);
    }

    public function getNomMarque()
    {
        $this->__load();
        return parent::getNomMarque();
    }

    public function setPngUrl($pngUrl)
    {
        $this->__load();
        return parent::setPngUrl($pngUrl);
    }

    public function getPngUrl()
    {
        $this->__load();
        return parent::getPngUrl();
    }

    public function setContent($content)
    {
        $this->__load();
        return parent::setContent($content);
    }

    public function getContent()
    {
        $this->__load();
        return parent::getContent();
    }

    public function setMarqueLien($marqueLien)
    {
        $this->__load();
        return parent::setMarqueLien($marqueLien);
    }

    public function getMarqueLien()
    {
        $this->__load();
        return parent::getMarqueLien();
    }

    public function jsonSerialize()
    {
        $this->__load();
        return parent::jsonSerialize();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idMarque', 'nomMarque', 'pngUrl', 'content', 'marqueLien');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}