<?php

namespace Proxies\__CG__\Yomaah\structureBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Png extends \Yomaah\structureBundle\Entity\Png implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setPngId($pngId)
    {
        $this->__load();
        return parent::setPngId($pngId);
    }

    public function getPngId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["pngId"];
        }
        $this->__load();
        return parent::getPngId();
    }

    public function setPngUrl($pngUrl)
    {
        $this->__load();
        return parent::setPngUrl($pngUrl);
    }

    public function getPngUrl()
    {
        $this->__load();
        return parent::getPngUrl();
    }

    public function setPngCategory($pngCategory)
    {
        $this->__load();
        return parent::setPngCategory($pngCategory);
    }

    public function getPngCategory()
    {
        $this->__load();
        return parent::getPngCategory();
    }

    public function addArticle(\Yomaah\structureBundle\Entity\Article $articles)
    {
        $this->__load();
        return parent::addArticle($articles);
    }

    public function removeArticle(\Yomaah\structureBundle\Entity\Article $articles)
    {
        $this->__load();
        return parent::removeArticle($articles);
    }

    public function getArticles()
    {
        $this->__load();
        return parent::getArticles();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'pngId', 'pngUrl', 'pngCategory', 'articles');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}