<?php

namespace Proxies\__CG__\Yomaah\structureBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class PageTest extends \Yomaah\structureBundle\Entity\PageTest implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setToken($path)
    {
        $this->__load();
        return parent::setToken($path);
    }

    public function getToken()
    {
        $this->__load();
        return parent::getToken();
    }

    public function setPageId($pageId)
    {
        $this->__load();
        return parent::setPageId($pageId);
    }

    public function getPageId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["pageId"];
        }
        $this->__load();
        return parent::getPageId();
    }

    public function setPageUrl($pageUrl)
    {
        $this->__load();
        return parent::setPageUrl($pageUrl);
    }

    public function getPageUrl()
    {
        $this->__load();
        return parent::getPageUrl();
    }

    public function addArticle(\Yomaah\structureBundle\Entity\Article $articles)
    {
        $this->__load();
        return parent::addArticle($articles);
    }

    public function removeArticle(\Yomaah\structureBundle\Entity\Article $articles)
    {
        $this->__load();
        return parent::removeArticle($articles);
    }

    public function getArticles()
    {
        $this->__load();
        return parent::getArticles();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'pageId', 'pageUrl', 'token', 'articles');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}