<?php

namespace Proxies\__CG__\Yomaah\structureBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Article extends \Yomaah\structureBundle\Entity\Article implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setArtId($artId)
    {
        $this->__load();
        return parent::setArtId($artId);
    }

    public function getArtId()
    {
        $this->__load();
        return parent::getArtId();
    }

    public function setArtDate($artDate)
    {
        $this->__load();
        return parent::setArtDate($artDate);
    }

    public function getArtDate()
    {
        $this->__load();
        return parent::getArtDate();
    }

    public function setTagName($tagName)
    {
        $this->__load();
        return parent::setTagName($tagName);
    }

    public function getTagName()
    {
        $this->__load();
        return parent::getTagName();
    }

    public function setArtContent($artContent)
    {
        $this->__load();
        return parent::setArtContent($artContent);
    }

    public function getArtContent()
    {
        $this->__load();
        return parent::getArtContent();
    }

    public function setArtSource($artSource)
    {
        $this->__load();
        return parent::setArtSource($artSource);
    }

    public function getArtSource()
    {
        $this->__load();
        return parent::getArtSource();
    }

    public function setArtLien($artLien)
    {
        $this->__load();
        return parent::setArtLien($artLien);
    }

    public function getArtLien()
    {
        $this->__load();
        return parent::getArtLien();
    }

    public function setArtImgUrl($artImgUrl)
    {
        $this->__load();
        return parent::setArtImgUrl($artImgUrl);
    }

    public function getArtImgUrl()
    {
        $this->__load();
        return parent::getArtImgUrl();
    }

    public function setPage(\Yomaah\structureBundle\Entity\Page $page = NULL)
    {
        $this->__load();
        return parent::setPage($page);
    }

    public function getPage()
    {
        $this->__load();
        return parent::getPage();
    }

    public function setPng(\Yomaah\structureBundle\Entity\Png $png = NULL)
    {
        $this->__load();
        return parent::setPng($png);
    }

    public function getPng()
    {
        $this->__load();
        return parent::getPng();
    }

    public function setArtTitle($artTitle)
    {
        $this->__load();
        return parent::setArtTitle($artTitle);
    }

    public function getArtTitle()
    {
        $this->__load();
        return parent::getArtTitle();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'artId', 'artDate', 'artTitle', 'artContent', 'artSource', 'artLien', 'artImgUrl', 'tagName', 'page', 'png');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}