<?php

namespace Yomaah\structureBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Yomaah\structureBundle\Entity\Page;

/**
 * articleRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepo extends EntityRepository
{
    public function findByPage(Array $param)
    {
        if ($param['idSite'] === null)
        {
            $query = $this->getEntityManager()
                ->createQuery('select a, p from yomaahBundle:Article a join a.page p where p.pageUrl = :url and p.site is null order by a.artId asc')
                ->setParameter('url',$param['pageUrl']);
        }else if ($param['idSite'] === false)
        {
            $query = $this->getEntityManager()
                ->createQuery('select a, p from yomaahBundle:Article a join a.page p where p.pageUrl = :url order by a.artId asc')
                ->setParameter('url', $param['pageUrl']);
        }else
        {
            $query = $this->getEntityManager()
                ->createQuery('select a, p from yomaahBundle:Article a join a.page p where p.pageUrl = :url and p.site = :site order by a.artId asc')
                ->setParameters(array('url' => $param['pageUrl'], 'site' => $param['idSite']));
            
        }
        return $query->getResult();
    }

    public function findDefaultArticle(Array $param)
    {
        $em = $this->getEntityManager();
        $new = new Article();
        $new->setArtTitle('Mon titre');
        $new->setArtContent('<p>Ceci est un article</p>');
        $new->setArtDate(new \Datetime());
        $new->setPng($em->getRepository('yomaahBundle:Png')->find(3));
        $new->setPage($param['page']);
        $new->setArtId($this->getNewId($param, $em));
        $em->persist($new);
        $em->flush();
        return $new;
    }

    public function getNewId(Array $param, $em)
    {
        if ($param['idSite'] === null)
        {
            $sql = 'select max(a.artId) from yomaahBundle:Article a join a.page p where p.pageUrl = :url and p.site is null';
            $query = $em->createQuery($sql)->setParameter('url',$param['page']->getPageUrl());

        }else if ($param['idSite'] === false)
        {
            $sql = 'select max(a.artId) from yomaahBundle:Article a join a.page p where p.pageUrl = :url';
            $query = $em->createQuery($sql)->setParameter('url',$param['page']->getPageUrl());
            
        }else
        {
            $sql =  'select max(a.artId) from yomaahBundle:Article a join a.page p join p.site s where p.pageUrl= :url and s.idSite = :site';
            $query = $em->createQuery($sql)
                ->setParameters(array('site' => $param['idSite'], 'url' => $param['page']->getPageUrl()));
        }
        $id = $query->getSingleResult(); 
        $maxId = (int) $id[1] + 1;

        /**
         * Début == 0
         */
        if ($param['position'] == "0")
        {
            if ($param['idSite'] === null)
            {
                $query = $this->getEntityManager()
                    ->createQuery('select a from yomaahBundle:Article a join a.page p where p.pageUrl = :url and p.site is null order by a.artId asc')
                        ->setParameter('url',$param['page']->getPageUrl());

            }else if ($param['idSite'] === false)
            {
                $query = $this->getEntityManager()
                    ->createQuery('select a from yomaahBundle:Article a join a.page p where p.pageUrl = :url order by a.artId asc')
                        ->setParameter('url',$param['page']->getPageUrl());
                
            }else
            {
                $query = $this->getEntityManager()
                    ->createQuery('select a from yomaahBundle:Article a join a.page p join p.site s where p.pageUrl = :url and s.idSite =:site order by a.artId asc')
                    ->setParameters(array('url' => $param['page']->getPageUrl(),'site' => $param['idSite']));
            }
            $articles = $query->getResult();
            $nb = count($articles);
            $minId = $articles[0]->getArtId();
            for ($i = 0; $i < $nb;$i++)
            {
                if ($i != $nb - 1)
                {
                    $this->changeId($articles[$i],$articles[$i+1]);
                }else
                {
                    $articles[$i]->setArtId($maxId);
                }
            }
            $j = $nb - 1;
            foreach ($articles as $a)
            {
                $this->getEntityManager()->createQuery('update yomaahBundle:Article a set a.artId = :artId where a.id = :id')
                    ->setParameters(array('artId' => $articles[$j]->getArtId(),'id' => $articles[$j]->getId()))
                    ->execute();
                $j--;
            }
            return $minId;
        }else
        {
            return $maxId;
        }
    }

    private function changeId($first, $second)
    {
        $first->setArtId($second->getArtId());
    }
}
