<?php

namespace Yomaah\structureBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MenuRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuTestRepo extends EntityRepository
{
    public function getLeftMenuTest(Array $param)
    {
        return $this->getEntityManager()->createQuery('select m from yomaahBundle:MenuTest m where m.position=0 and m.token = :token')
            ->setParameter('token', $param['token'])
            ->getResult();
    }

    public function getRightMenuTest(Array $param)
    {
        return $this->getEntityManager()->createQuery('select m from yomaahBundle:MenuTest m where m.position=1 and m.token = :token')
            ->setParameter('token', $param['token'])
            ->getResult();
    }
}
