<?php

namespace Yomaah\structureBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MenuRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepo extends EntityRepository
{
    public function getLeftMenu($site = null)
    {
        if ($site == null)
        {
            return $this->getEntityManager()->createQuery('select m from yomaahBundle:Menu m where m.position=0')->getResult();
            
        }else
        {
            return $this->getEntityManager()->createQuery('select m from yomaahBundle:Menu m where m.position=0 and m.site = :site')
                ->setParameter('site', $site)
                ->getResult();
        }
        /**
         * En prod
         * return $this->getEntityManager()->createQuery('select m from yomaahBundle:Menu m where m.position=0')->getResult();
         **/
    }

    public function getRightMenu($site = null)
    {
        if ($site == null)
        {
            return $this->getEntityManager()->createQuery('select m from yomaahBundle:Menu m where m.position=1')->getResult();
        }else
        {
            return $this->getEntityManager()->createQuery('select m from yomaahBundle:Menu m where m.position=1 and m.site = :site')
                ->setParameter('site', $site)
                ->getResult();
        }
    }
}
